// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANSeeM6TG-WuOyUcgaKQJI9dZ2tZl-Hz8',
    appId: '1:85536554061:web:86c7e9b0cd3be2fdcbf004',
    messagingSenderId: '85536554061',
    projectId: 'uber-45632',
    authDomain: 'uber-45632.firebaseapp.com',
    databaseURL: 'https://uber-45632-default-rtdb.firebaseio.com',
    storageBucket: 'uber-45632.firebasestorage.app',
    measurementId: 'G-C9GR94334M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0evZ5mnXkBDiRFZAnsO8ggTMWiUuedJ4',
    appId: '1:85536554061:android:45f523a4bdc63ad1cbf004',
    messagingSenderId: '85536554061',
    projectId: 'uber-45632',
    databaseURL: 'https://uber-45632-default-rtdb.firebaseio.com',
    storageBucket: 'uber-45632.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn7U1ggBsilKlCck2mj47J2wc3fX2v2yM',
    appId: '1:85536554061:ios:fcf5543301a2b3eccbf004',
    messagingSenderId: '85536554061',
    projectId: 'uber-45632',
    databaseURL: 'https://uber-45632-default-rtdb.firebaseio.com',
    storageBucket: 'uber-45632.firebasestorage.app',
    iosBundleId: 'com.example.uberDbProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn7U1ggBsilKlCck2mj47J2wc3fX2v2yM',
    appId: '1:85536554061:ios:fcf5543301a2b3eccbf004',
    messagingSenderId: '85536554061',
    projectId: 'uber-45632',
    databaseURL: 'https://uber-45632-default-rtdb.firebaseio.com',
    storageBucket: 'uber-45632.firebasestorage.app',
    iosBundleId: 'com.example.uberDbProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANSeeM6TG-WuOyUcgaKQJI9dZ2tZl-Hz8',
    appId: '1:85536554061:web:e8a97bbd8d76845bcbf004',
    messagingSenderId: '85536554061',
    projectId: 'uber-45632',
    authDomain: 'uber-45632.firebaseapp.com',
    databaseURL: 'https://uber-45632-default-rtdb.firebaseio.com',
    storageBucket: 'uber-45632.firebasestorage.app',
    measurementId: 'G-TL2HS77WGC',
  );
}
